swagger: '2.0'
info:
  description: ABC banking  API
  title: ABC banking  API
  version: 1.0.0
host: 'localhost:8080'
schemes:
  - http
basePath: /
produces:
  - application/json
paths:
  /account:
    post:
      summary: Get Accounts
      consumes:
        - application/json
      parameters:
        - in: body
          name: account
          description: Return account holded by User.
          schema:
            type: object
            required:
              - accountNumber
            properties:
              accountNumber:
                type: string
      responses:
        '200':
          description: A account object
          examples:
            application/json:
              List:
                - accountNumber: 10001
                  balanceAmount: 400
                - accountNumber: 10098
                  balanceAmount: 200
                - accountNumber: 12346
                  balanceAmount: 200
          schema:
            $ref: '#/definitions/ArrayOfAccountandBalance'
            
  /transaction:
    post:
      summary: Get transaction
      consumes:
        - application/json
      parameters:
        - in: body
          name: account
          description: Return transaction holded by account.
          schema:
            type: object
            required:
              - userID
            properties:
              userID:
                type: string
              firstName:
                type: string
              lastName:
                type: string
      responses:
        '200':
          description: A account object
          examples:
            application/json:
              List:
                - accountNumber: 10001
                  transactionId: 1233121341
                  transactionAmount: 100
                  balanceAmount: 200
                - accountNumber: 10001
                  transactionId: 123223222411
                  transactionAmount: 100
                  balanceAmount: 200
                - accountNumber: 10001
                  transactionId: 123382211
                  transactionAmount: 1200
                  balanceAmount: 400
          schema:
            $ref: '#/definitions/ArrayOfTransaction'
        
definitions:
  ArrayOfAccountandBalance:
    type: object
    properties:
      accountNumner:
        type: integer
        example: 10001
        description: The user accountNumner.
      balanceAmount:
        type: string
        example: 200
        description: The user balanceAmount with respect to account number.
  ArrayOfTransaction:
    type: object
    properties:
      accountNumber:
        type: integer
        example: 10001
        description: The user accountNumber.
      transactionId:
        type: string
        example: 200
        description: The user transactionId with respect to account number.
      transactionAmount:
        type: string
        example: 200
        description: >-
          The user transactionAmount with respect to account number and
          transactionId.
      balanceAmount:
        type: string
        example: 200
        description: The user balanceAmount with respect to account number.
